"""Pure pricing formulae — no side effects, no I/O, fully typed.

All money values use Decimal to avoid float rounding errors.
All functions are pure: same inputs → same outputs, no state.
"""

from __future__ import annotations

from decimal import ROUND_HALF_UP, Decimal

from .constants import PLATFORM_SPREAD, PLATFORM_TOKEN_RATE


def split_revenue(base_fee: Decimal) -> tuple[Decimal, Decimal]:
    """
    Split a single agent's base_fee into (developer_payout, platform_cut).

    Developer receives: base_fee × (1 - PLATFORM_SPREAD)
    Platform receives:  base_fee × PLATFORM_SPREAD

    Returns:
        (developer_payout, platform_cut) — both 8 decimal places
    """
    platform_cut = (base_fee * PLATFORM_SPREAD).quantize(
        Decimal("0.00000001"), rounding=ROUND_HALF_UP
    )
    developer_payout = base_fee - platform_cut
    return developer_payout, platform_cut


def split_revenue_dan(
    base_fee: Decimal,
    *,
    coordinator_share_bps: int = 0,
    validator_share_bps: int = 0,
) -> tuple[Decimal, Decimal, Decimal]:
    """
    DAN three-way split: (agent_share, validator_share, coordinator_share).

    BPS values are basis points of base_fee (500 = 5%). Remainder goes to agent.
    """
    coordinator_cut = (
        base_fee * Decimal(coordinator_share_bps) / Decimal(10000)
    ).quantize(Decimal("0.00000001"), rounding=ROUND_HALF_UP)
    validator_cut = (
        base_fee * Decimal(validator_share_bps) / Decimal(10000)
    ).quantize(Decimal("0.00000001"), rounding=ROUND_HALF_UP)
    agent_share = base_fee - coordinator_cut - validator_cut
    if agent_share < 0:
        raise ValueError("fee shares exceed base_fee")
    return agent_share, validator_cut, coordinator_cut


def compute_turn_cost(base_fees: list[Decimal], platform_output_tokens: int) -> Decimal:
    """
    Compute total cost charged to the user for one SuperAgent turn.

    turn_cost = sum(base_fees) + PLATFORM_TOKEN_RATE × output_tokens

    Args:
        base_fees: base_fee for each successful A2A/ACP agent call in the turn
        platform_output_tokens: number of output tokens generated by SuperAgent

    Returns:
        turn_cost as Decimal, rounded to 8 decimal places
    """
    base_total = sum(base_fees, Decimal("0"))
    token_cost = PLATFORM_TOKEN_RATE * Decimal(str(platform_output_tokens))
    return (base_total + token_cost).quantize(
        Decimal("0.00000001"), rounding=ROUND_HALF_UP
    )


def compute_arrears_minimum_topup(arrears: Decimal, interest_rate: Decimal) -> Decimal:
    """
    Minimum top-up required to clear arrears including accrued interest.

    min_topup = arrears × (1 + interest_rate)

    Returns:
        Minimum USDC amount the user must deposit to clear the arrears flag.
    """
    return (arrears * (Decimal("1") + interest_rate)).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )


def routing_score(
    *,
    success_rate: float,
    uptime_score: float,
    p95_latency_ms: int,
    base_fee_usd: Decimal,
    norm_latency: float,
    norm_base_fee: float,
) -> float:
    """
    Compute routing score for a single agent candidate (spec §12).

    Score = 0.4 × success_rate + 0.3 × uptime_score
            + 0.2 × (1 / norm_latency) + 0.1 × (1 / norm_base_fee)

    norm_latency  = p95_latency_ms / registry_median_latency_ms  (1.0 in bootstrap)
    norm_base_fee = base_fee_usd / registry_median_base_fee       (1.0 in bootstrap)

    Higher score = better candidate.  Scores are relative — compare within the
    same candidate set, not across different planning calls.
    """
    # Guard against division by zero (bootstrap values are always > 0 but be safe)
    lat_component = 1.0 / norm_latency if norm_latency > 0 else 0.0
    fee_component = 1.0 / norm_base_fee if norm_base_fee > 0 else 0.0

    return (
        0.4 * success_rate
        + 0.3 * uptime_score
        + 0.2 * lat_component
        + 0.1 * fee_component
    )
