#!/bin/bash
set -e

echo "MetaOrcha Frontend Setup from GitHub"
echo "========================================"

REPO_URL="https://github.com/AHA-orcha/metaorcha-control.git"
FRONTEND_DIR="/workspaces/metaorcha-emerge/frontend"
BACKUP_DIR="/workspaces/metaorcha-emerge/frontend.backup.$(date +%s)"

# Check if frontend directory exists
if [ -d "$FRONTEND_DIR" ]; then
    echo "📦 Frontend directory exists"
    
    # Check if it's a git repo
    if [ -d "$FRONTEND_DIR/.git" ]; then
        echo "🔄 Pulling latest changes from GitHub..."
        cd "$FRONTEND_DIR"
        
        # Check remote URL
        CURRENT_REMOTE=$(git remote get-url origin 2>/dev/null || echo "")
        if [ "$CURRENT_REMOTE" != "$REPO_URL" ]; then
            echo "⚠️  Remote URL mismatch. Expected: $REPO_URL"
            echo "   Current: $CURRENT_REMOTE"
            echo "   Updating remote URL..."
            git remote set-url origin "$REPO_URL"
        fi
        
        # Stash any local changes
        if ! git diff --quiet || ! git diff --cached --quiet; then
            echo "💾 Stashing local changes..."
            git stash push -m "Auto-stash before sync $(date)"
        fi
        
        # Pull latest
        git fetch origin
        git checkout main
        git pull origin main
        
        echo "✅ Frontend synced with GitHub"
    else
        echo "⚠️  Frontend exists but is not a Git repository"
        echo "   Backing up to: $BACKUP_DIR"
        mv "$FRONTEND_DIR" "$BACKUP_DIR"
        
        echo "📥 Cloning fresh from GitHub..."
        git clone "$REPO_URL" "$FRONTEND_DIR"
        cd "$FRONTEND_DIR"
        echo "✅ Frontend cloned successfully"
    fi
else
    echo "📥 Cloning frontend from GitHub..."
    git clone "$REPO_URL" "$FRONTEND_DIR"
    cd "$FRONTEND_DIR"
    echo "✅ Frontend cloned successfully"
fi

# Install dependencies
echo ""
echo "📦 Installing dependencies..."
cd "$FRONTEND_DIR"

if command -v bun &> /dev/null; then
    echo "   Using Bun..."
    bun install
elif command -v npm &> /dev/null; then
    echo "   Using npm..."
    npm install
else
    echo "❌ Neither Bun nor npm found. Please install Node.js or Bun."
    exit 1
fi

# Create .env file if it doesn't exist
if [ ! -f "$FRONTEND_DIR/.env" ]; then
    echo ""
    echo "📝 Creating .env file..."
    cat > "$FRONTEND_DIR/.env" << 'ENVEOF'
# MetaOrcha Frontend Environment Variables
# Generated by setup-frontend.sh

# API Configuration
VITE_API_BASE_URL=http://localhost:8000
VITE_GATEWAY_URL=http://localhost:8000
VITE_REGISTRY_URL=http://localhost:8001

# Notion Agent Configuration
VITE_NOTION_AGENT_URL=http://localhost:3003

# Environment
VITE_ENVIRONMENT=development

# Optional: Enable debug mode
# VITE_DEBUG=true
ENVEOF
    echo "✅ .env file created"
else
    echo ""
    echo "ℹ️  .env file already exists, skipping creation"
fi

echo ""
echo "✅ Frontend setup complete!"
echo ""
echo "📋 Next steps:"
echo "   1. Start backend services:"
echo "      cd /workspaces/metaorcha-emerge/mvp && docker-compose up -d"
echo ""
echo "   2. Start frontend development server:"
echo "      cd /workspaces/metaorcha-emerge/frontend"
echo "      npm run dev  (or: bun dev)"
echo ""
echo "   3. Open in browser:"
echo "      http://localhost:8080"
echo ""
echo "🔗 GitHub Repository: $REPO_URL"
echo "📁 Local Path: $FRONTEND_DIR"
