"""Verified Runs — assemble a per-run audit (evidence package) from transcript rows."""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal, InvalidOperation
from typing import Any

from ..persistence.transcript_store import TRANSCRIPT_TOOL_META_KEY
from .models import RunAuditResponse, RunAuditStep, RunAuditSummary

_AUDIT_NOTE = (
    "Generated by Orcha Verified Runs — per-step evidence of what each "
    "agent call did and its verdict."
)
_GOAL_MAX_LEN = 500


def _row_role(row: Any) -> str:
    r = getattr(row, "role", "")
    s = getattr(r, "name", None) or str(r)
    return s.rsplit(".", 1)[-1]


def _step_cost(meta: dict[str, Any]) -> Decimal:
    raw = meta.get("total_cost_usd")
    if not isinstance(raw, str) or not raw:
        return Decimal(0)
    try:
        return Decimal(raw)
    except InvalidOperation:
        return Decimal(0)


def build_run_audit(
    session_id: str,
    rows: list[Any],
    *,
    generated_at: datetime | None = None,
) -> RunAuditResponse:
    """
    Assemble the Verified Runs evidence package from SessionTranscriptEntry rows.

    Rows are Prisma records (or test fakes) with ``role`` / ``content`` /
    ``tool_inputs`` / ``created_at`` attributes. Steps come from TOOL rows whose
    ``tool_inputs`` carries the ``TRANSCRIPT_TOOL_META_KEY`` meta dict;
    ``invocation_args`` is deliberately omitted (may contain secrets).
    """
    generated_at = generated_at or datetime.now(UTC)

    goal = ""
    timestamps: list[datetime] = []
    for row in rows:
        created_at = getattr(row, "created_at", None)
        if isinstance(created_at, datetime):
            timestamps.append(created_at)
        if not goal and _row_role(row) == "USER":
            goal = str(getattr(row, "content", "") or "")[:_GOAL_MAX_LEN]

    steps: list[RunAuditStep] = []
    protocols: set[str] = set()
    total_cost = Decimal(0)
    for row in rows:
        if _row_role(row) != "TOOL":
            continue
        meta = getattr(row, "tool_inputs", None)
        # Persisted rows store the meta dict itself in tool_inputs; hydrated
        # messages nest it under TRANSCRIPT_TOOL_META_KEY. Accept both.
        if isinstance(meta, dict) and "agent_id" not in meta:
            nested = meta.get(TRANSCRIPT_TOOL_META_KEY)
            meta = nested if isinstance(nested, dict) else None
        if not isinstance(meta, dict) or "agent_id" not in meta:
            continue
        verified = meta.get("verified")
        verified = verified if isinstance(verified, bool) else True
        verdict_reason = str(meta.get("verdict_reason") or "ok")
        protocol = str(meta.get("protocol") or "")
        if protocol:
            protocols.add(protocol)
        total_cost += _step_cost(meta)
        steps.append(
            RunAuditStep(
                seq=len(steps) + 1,
                agent_id=str(meta.get("agent_id") or ""),
                capability_id=str(meta.get("capability_id") or ""),
                protocol=protocol,
                internal_tool_name=str(meta.get("internal_tool_name") or ""),
                verified=verified,
                verdict_reason=verdict_reason,
                base_fee=meta.get("base_fee")
                if isinstance(meta.get("base_fee"), str)
                else None,
                total_cost_usd=meta.get("total_cost_usd")
                if isinstance(meta.get("total_cost_usd"), str)
                else None,
            )
        )

    duration_ms: int | None = None
    if len(timestamps) >= 2:
        duration_ms = int((max(timestamps) - min(timestamps)).total_seconds() * 1000)

    return RunAuditResponse(
        session_id=session_id,
        generated_at=generated_at.isoformat(),
        goal=goal,
        summary=RunAuditSummary(
            total_steps=len(steps),
            steps_verified=sum(1 for s in steps if s.verified),
            steps_failed=sum(1 for s in steps if not s.verified),
            protocols=sorted(protocols),
            total_cost_usd=str(total_cost.normalize()),
            duration_ms=duration_ms,
        ),
        steps=steps,
        note=_AUDIT_NOTE,
    )
